### ISSUE TITLE
`success` in `timeout` needs a value

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#11]
On page 123

    def timeout(t: Long): Future[Unit] = {
      val p = Promise[Unit]
      timer.schedule(new TimerTask {
        def run() = {
          p success ()   // <<< p success (())
          timer.cancel()
        } 
      }, t)
      p.future 
    }

It's only a warning, but still ;)

**Comment by axel22** [comment]
I corrected this in the code repository to avoid the warning.
