### ISSUE TITLE
Q: timeout & callback

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#12]
On page 124 you stated

>The future returned by timeout can be used to install a callback

Are the following mental extensions correct?

>The future returned by timeout can be used to install a callback which will be called not before the timeout 

>The future returned by timeout can be used to install a callback which will be called after the timeout occurred

**Comment by axel22** [comment]
> The future returned by timeout can be used to install a callback which will be called not before the timeout.

Yes.

> The future returned by timeout can be used to install a callback which will be called after the timeout occurred.

Yes.
