### ISSUE TITLE
Something wrong in ch9 about ParLongAccumulator

### ISSUE THREAD

**Issue by fairjm** [concurrent-programming-in-scala/learning-examples#14]
The source code:    

	  class ParLongAccumulator(z: Long)(op: (Long, Long) => Long) {
		private val par = Runtime.getRuntime.availableProcessors * 128
		private val values = new AtomicLongArray(par)
		@tailrec final def add(v: Long): Unit = {
		  val id = Thread.currentThread.getId.toInt
		  val i = math.abs(scala.util.hashing.byteswap32(id)) % par
		  val ov = values.get(i)
		  val nv = op(ov, v)
		  if (!values.compareAndSet(i, ov, nv)) add(v)
		}
		def apply(): Long = {
		  var total = 0L
		  for (i <- 0 until values.length) total = op(total, values.get(i))
		  total
		}
	  }
missing `z`.maybe `total=0L` should be placed by `total=z`

**Comment by axel22** [comment]
You're right, thanks for pointing it out.
I added this to the Errata document with a thank-you note.

http://concurrent-programming-in-scala.github.io/pages/errata.html
