### ISSUE TITLE
CH3 FileSystem

### ISSUE THREAD

**Issue by rafaeltrrs112** [concurrent-programming-in-scala/learning-examples#18]
Hello Alex, 

First I wanna thank you for makings this book. Currently taking Parallel Computing at SUNY Oswego with Professor Doug Lea. I think there is a race condition in your CH3 FileSystem example. When the logger is created in the constructor it may access the messages queue before it is instantiated below, resulting in a NullPointerException. I just fixed the issue by pulling up the line instantiating the messages queue up before the logger is created. 

Again, thank you for creating your book, it is helping me through Professor Lea's class immensely. Cheers.

**Comment by axel22** [comment]
Hi Rafael!

You are indeed correct - great catch! I applied a patch: https://github.com/concurrent-programming-in-scala/learning-examples/commit/eb188abe16cb3c86f4eb18b5c852af4f327bf29a

**Comment by axel22** [comment]
Thanks a lot for reporting, and glad to hear you're enjoying the book!
