### ISSUE TITLE
Example org.learningconcurrency.ch6.ObservablesSubscriptions runs infinitely

### ISSUE THREAD

**Issue by sunrenjie** [concurrent-programming-in-scala/learning-examples#25]
We'd expect subscription.unsubscribe() to causes fileMonitor.stop() to be invoked. But that is not the case. In my environment, the monitor runs infinitely. Any suggestions?

**Comment by ryblovAV** [comment]
I changed the method to create Observable: 
Observable.create instead of Observable.apply

**Comment by sunrenjie** [comment]
Well, with that change applied, this class now works as expected (just note the signatures !). Sorry I didn't read the code in the book carefully enough. :)
