### ISSUE TITLE
Is the CAS implemention demo wrong?

### ISSUE THREAD

**Issue by amoszhou** [concurrent-programming-in-scala/learning-examples#26]
in the page 113 of the book:
def compareAndSet(ov: Long, nv: Long): Boolean=
this.synchronized {
if (this.get == ov) false else {
this.set(nv)
true
}
}

Is the result of condition  wrong ?  
`if (this.get == ov) this.set(nv)
true 
else {
false
}`

?

**Comment by axel22** [comment]
Yes - that's been reported, and the correction is in the book errata:

http://concurrent-programming-in-scala.github.io/pages/errata.html

Thanks for bringing this up!

**Comment by amoszhou** [comment]
you are welcome, book is very Nice.
