### ISSUE TITLE
What does 'the last event' mean in Ex4 of Ch6 ?

### ISSUE THREAD

**Issue by ssmylh** [concurrent-programming-in-scala/learning-examples#27]
I don't know what 'the last event' means in Exercise 4 of Chapter 6.
With this [answer](https://github.com/concurrent-programming-in-scala/learning-examples/blob/5347792878a9824821ebde039c666345426a2a6b/src/main/scala/org/learningconcurrency/exercises/ch6/Ex4.scala), 'the last event' means the event emitted just before completed:

```
val o = Subject[String]()
val s = o.toSignal

o.onNext("a")
println(s()) // null

o.onNext("b")
println(s()) // null

o.onCompleted()
println(s()) // b
```

But I guess that 'the last event' means the event emitted just before `Signal.apply` is called:

```
val o = Subject[String]()
val s = o.toSignal

o.onNext("a")
println(s()) // a

o.onNext("b")
println(s()) // b

o.onCompleted()
println(s()) // b
```
What does 'the last event' mean ?

**Comment by axel22** [comment]
Good catch - the last event is meant to be the "latest" event, as in the last event emitted before `Signal.apply` is called.

The answer there is incorrect in this sense. We should fix that - do you maybe have a patch already?

**Comment by ssmylh** [comment]
I can create a PR in a few days !

**Comment by ssmylh** [comment]
Created PR.
Please review.
