### ISSUE TITLE
CAS example 

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#8]
On page 69 you state:

> The compare-and-set operation, sometimes called compare-and-swap (CAS), takes the expected previous value and the new value for the atomic variable and atomically replaces the current value with the new value only if the current value is equal to the expected value.

With respect to your code example, I guess "the expected previous value" is `ov`, and "the new value" is `nv`.

    def compareAndSet(ov: Long, nv: Long): Boolean =
      this.synchronized {
        if (this.get == ov) false else {
          this.set(nv)
          true
        } 
      }

So, "if the current value is equal to the expected value" translates to `if (this.get == ov)`. If equality holds the replacement is executed. But within the code snippet it is the other way around, no?

**Comment by axel22** [comment]
Wow. I think you actually spotted a typo that 5 reviewers and myself were not able to spot.
The snippet should have been:

    def compareAndSet(ov: Long, nv: Long): Boolean =
      this.synchronized {
        if (this.get != ov) false else {
          this.set(nv)
          true
      }

Seems like we will have to release an errata document for the book to address this.

**Comment by axel22** [comment]
Ok, added the website for the book, along with [errata and a thank you note](http://concurrent-programming-in-scala.github.io/pages/errata.html).

Thanks!
