### ISSUE TITLE
`AtomicBuffer#+=` needs to be final or private

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#9]
Hi,

    class AtomicBuffer[T] {
    
      private val buffer = new AtomicReference[List[T]](Nil)
    
      @tailrec def +=(x: T): Unit = {
        val xs = buffer.get
        val nxs = x :: xs
        if (!buffer.compareAndSet(xs, nxs))
          this += x // retry
        else ()
      }
    
    }

I get the following compiler error:

    could not optimize @tailrec annotated method +=: it is neither private nor final so can be overridden

Adding `final` works just fine.

**Comment by axel22** [comment]
Nice catch.
Added to [errata](http://concurrent-programming-in-scala.github.io/pages/errata.html).
